### ISSUE TITLE
MvvmDialogs

### ISSUE THREAD

**Issue by mysteryx93** [klemmchr/MvvmBlazor#106]
### Feature description

[I developed this framework](https://github.com/mysteryx93/HanumanInstitute.MvvmDialogs) to provide simple dialogs handling in MVVM.

It currently has implemented for WPF and Avalonia. I believe Blazor support could be added rather easily, but it just takes someone to do it. Would you be interested in implementing MvvmDialogs for Blazor? Seems like the perfect complement for your framework.

Just copy/paste MvvmDialogs.Avalonia and then edit the platform-specific code. If you do, let me know if you run into any problems and I can help with the library code structure and shared code.

**Comment by klemmchr** [comment]
I have no intention of adding such code as this is out of scope for this library. Handling dialogs is typically done via some form of service but since this depends on the component library used there would be no benefit to add such functionality. Using dialogs in Blazor usually is easy to do and requires no framework of some sort.
