### ISSUE TITLE
Why is the lifetime of scoped view models tied to the component lifetime instead of the request lifetime?

### ISSUE THREAD

**Issue by pm64** [klemmchr/MvvmBlazor#120]
### Question

According to the docs, "If you register a view model as scoped it will be tied to the lifetime of the component and disposed when the component is disposed."

I'm sure there's a good explanation for this -- but for me, this design doesn't reconcile with the behavior of scoped dependencies in general, which are tied to the request lifetime.

It sounds like in this case, when a component inherits from `MvvmComponentBase<T>` , MvvmBlazor disposes the view model when the component is disposed -- where normally (for example, when the component inherits from `MvvmComponentBase`), the view model would live on.

Am I understanding this correctly? I know there's no way to tie a dependency to the lifetime of a component, so maybe scoped was just the "best fit" for your design?

### Version

6.0.6

### Are you using Blazor WASM or Blazor Server?

Blazor WASM

**Comment by klemmchr** [comment]
> I'm sure there's a good explanation for this -- but for me, this design doesn't reconcile with the behavior of scoped dependencies in general, which are tied to the request lifetime.

This originates back to when I was developing this library initially to use it in a Blazor serverside project that used EF. Since Blazor didn't have the classical scoped approach per request like ASP.NET Core did, I thought about how to deal with disposable dependencies in general. The naive approach was to make an mvvm component behave like an owning component to ensure proper disposing of dependencies.

> It sounds like in this case, when a component inherits from MvvmComponentBase<T> , MvvmBlazor disposes the view model when the component is disposed -- where normally (for example, when the component inherits from MvvmComponentBase), the view model would live on.

Yes, that's correct.

> Am I understanding this correctly? I know there's no way to tie a dependency to the lifetime of a component, so maybe scoped was just the "best fit" for your design?

It was a (really bad) compromise. And it was based on the idea to redefine the way scopes work in Blazor. No big surprise that this backfires at some point.

For example #109 only exists because of this behavior. Rewriting it is a major change that basically breaks everything.

**Comment by pm64** [comment]
Thanks @klemmchr for the thoughtful response. I don't personally think the compromise was bad, just requires some explanation for the uninitiated. Grateful for all you do!
