### ISSUE TITLE
Any guidance on how to use MVVMBlazor with Fluxor for state management

### ISSUE THREAD

**Issue by danglingneuron** [klemmchr/MvvmBlazor#38]
Planning a large LOB ASP.Net Core/BlazorWASM project. Shared state management across components/modules and local data caching is needed.

My initial impression is that MVVM/Fluxor overlap/clash at the UI front.

Fluxor also hooks into the razor components to update the view. **Razor components need to inherit FluxorComponent**. But the whole redux pattern is great for shared state management across components. Any suggestions on how to use Fluxor with MVVM?

**Comment by pm64** [comment]
I'm not aware of any way for these libraries to coexist. You would choose one -- MVVMBlazor if you prefer mutable state, Fluxor if you prefer immutable.

**Comment by klemmchr** [comment]
I don't really know Fluxor, however as @pm64 mentioned both libraries aim at the same principle while Fluxor is for state management and MVVM isn't. You can't mix both concepts. If you look at the Flux pattern you can spot these differences:

![](https://github.com/mrpmorris/Fluxor/raw/master/Images/flux-pattern.jpg)

MVVM is for abstraction layer between the view and the business logic. Flux aims to achieve the same abstraction while providing a state management. 

If you need state management, just stick to Fluxor. It offers everything you need. If you don't need state management go for MVVM.

**Comment by pm64** [comment]
I would just add that for many people, "state management" refers to the ability to have a state object shared between components, typically for the purpose of affecting UI when necessary. This is a huge deal in Javascript, and a big part of the reason libraries like Redux are so ubiquitous. But we get this ability for free with ASP.Net using dependency injection.

There might be another concept of "state management" in which the term refers to the manner in which the state is manipulated, but I believe this sense of the term also applies to both Fluxor and MVVMBlazor.

In Fluxor, the state is immutable -- in other words, a change in state happens by replacing the entire state object with an updated state object instance. Fluxor provides functionality to help perform these operations.

In MVVMBlazor, state is mutable, meaning that your state object doesn't change, but its property values do. Because changes in state happen by simply assigning new property values, no special functionality is needed to facilitate management of the state -- you're just performing normal C# assignments whenever you want.

**Comment by mrpmorris** [comment]
You don't have to descend from FluxorComponent, that's just a convenience class.

Instead you can subscribe to the Changed event of each IState you consume.
