### ISSUE TITLE
CascadingParameter availability

### ISSUE THREAD

**Issue by Levinta** [klemmchr/MvvmBlazor#45]
Hello,
While looking at your samples, I could find a lot of useful information.
However, I couldn't find anything about CascadingParameter usage.

I tried to pass a string parameter and it is always null.
in view model:
```
[CascadingParameter]
 public string SomeValue { get; set; }
```

and in a parent component 
`<CascadingValue Value="AStringProperty">...</CascadingValue>`

Also, 
I'm using 
<CascadingAuthenticationState> in App.Razor which should be available as a cascading a param, as well.

```
[CascadingParameter]
 public Task<AuthenticationState> AuthenticationStateTask { get; set; }
```
It is also null in the view model

Could you please advise?

Thank you in advance

**Comment by klemmchr** [comment]
Currently there is no support for cascading parameters. I might introduce it in the future, this one is also up for grabs.

**Comment by pm64** [comment]
Is it appropriate for view models to take cascading parameters? My feeling is that you'd want the component to receive such parameters, setting view model properties in OnParametersSet() as necessary. After all, the cascading parameter could be completely unrelated to the view model or UI. I understand that in MvvmBlazor, the view model can patch into the component's lifecycle, etc.. but even this feels like an infringement on the boundary between the component and the view model, and is beyond what we expect in terms of view model behavior in WPF, Xamarin.Forms, and other frameworks that utilize the MVVM pattern. Are there important use cases here I'm just failing to see?

**Comment by klemmchr** [comment]
> Is it appropriate for view models to take cascading parameters?

Generally speaking I don't really see an issue with that. According to the [docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/cascading-values-and-parameters?view=aspnetcore-5.0), CascadingParameters can be anything and are not explicitly related to any UI stuff whatsoever. 

> After all, the cascading parameter could be completely unrelated to the view model or UI.

It _can_ be. But that does not mean that this is the case for all cases.

> I understand that in MvvmBlazor, the view model can patch into the component's lifecycle, etc.. but even this feels like an infringement on the boundary between the component and the view model, and is beyond what we expect in terms of view model behavior in WPF, Xamarin.Forms, and other frameworks that utilize the MVVM pattern.

Patching into the lifecycle of a component isn't a violation of MVVM imo. Escpecially since you can achieve the same behavior in Xamarin.Forms and WPF too. It's not uncommon to have an event to command binding for initialization or other lifecycle events. However, this always requires boilerplate code which isn't really feasible. Hence the possibility to use them in the view model directly.

> Are there important use cases here I'm just failing to see?

Actually I would also be interested in a particular use case for CascadingParameters in the view model. The example shows something about Authentication, by looking on it I would say that this is more of a general structural problem than just a lack of features.

**Comment by dugsteen** [comment]
I'll offer a use case: Telerik Dialogs. For those unfamiliar, the [Telerik dialog components](https://docs.telerik.com/blazor-ui/components/dialog/predefined) make use of a single DialogFactory which is cascaded down through the hierarchy to be used anywhere. I would like to be able to use it in the viewmodel, but as of now I must write code in the razor page instead. Not a huge deal, but anti-pattern to be sure.

BTW, I see that this is marked as "help wanted". I'd be happy to take a crack at it, but haven't gotten too deep in the code yet. If someone wanted to point me in the right direction, I could give it a go. Thanks!

**Comment by klemmchr** [comment]
> BTW, I see that this is marked as "help wanted". I'd be happy to take a crack at it, but haven't gotten too deep in the code yet. If someone wanted to point me in the right direction, I could give it a go. Thanks!

Sorry for the late response. I could certainly give you some starting points if you want to. I would recommend that we postpone this after I did a couple of breaking changes to address #57.

**Comment by deveshbahuguna** [comment]
@klemmchr  There is a use case for cascading parameter in our app too. If you need help, I can also try to work on that.

**Comment by dugsteen** [comment]
Since I first posted, I've gotten busier and can't help directly right now. However, I do know the issue, so if you need someone to check (e.g. with the Telerik controls), I could do that. Good luck!

**Comment by SenuinLentar** [comment]
Hello,
I have a similar use case for CascadingParameters in ViewModel classes.
Is there any news about this ?

**Comment by klemmchr** [comment]
This will be available with the next update.
