### ISSUE TITLE
Can the CodeGenerators be bundled with the nuget package?

### ISSUE THREAD

**Issue by tancyew** [klemmchr/MvvmBlazor#71]
Sorry, i'm quite a new when it comes to library and source code generators. 

I'm just wondering if the CodeGenerators project which helps to generate private property field flagged with NotifyAttribute can be included in the main nuget library?

I can see that it helps to reduce a lot of boilerplate codes, but maybe there are some disadvantages that I'm missing. Please kindly share your view.

**Comment by klemmchr** [comment]
There is actual a technical limitation to this. Since Visual Studio itself is not running on .NET Core, any code analyzer package (or in this case source generator) needs to target .netstandard2.0. This is stated in the [docs](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview).

Therefore putting the generator into the same library is not doable at the moment. However, I could adopt the pattern of having a core library besides the main library and then have references from the main library to the core library and the analyzers. xUnit is doing the same. 

I definitely see the need for having everything in one project reference to have the support for the INPC generator without the need for additional references.

**Comment by klemmchr** [comment]
With the upcoming version there will be three different packages:

- `MvvmBlazor` (main package as usual)
- `MvvmBlazor.Core` (core functionality of MvvmBlazor)
- `MvvmBlazor.CodeGenerators` (code generators for custom components and INPC)

`MvvmBlazor` will reference the other two packages. This way, users could still opt out of code generators.

**Comment by tancyew** [comment]
Thanks for the prompt response, can't wait for it to happen. Thanks for all the hard work!

**Comment by klemmchr** [comment]
> Thanks for the prompt response, can't wait for it to happen. Thanks for all the hard work!

You don't have to wait, the release has been published yesterday. Happy coding 😄

**Comment by tancyew** [comment]
wow you are awesome mate. thanks! sorry for late reply, not too active in github. 

You guys are my inspiration that someday I can be like you guys, creating library for the community, unfortunately my skill set doesn't seems to be at the level yet :(
